name: Benchmark

on:
  workflow_dispatch:

jobs:
  Benchmark:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64:latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install finufft
    - name: Install finufft-benchmark
      run: pip install .
    - name: rum benchmark
      run: finufft-benchmark run